# A simple action usage
name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-22.04-arm
    permissions:
      contents: read
    steps:
      - name: Get clang
        run: echo $PWD; mkdir /home/runner/work/kernel_build_action/kernel_build_action/clang;wget -q https://github.com/tomxi1997/Toolchain-for-aarch64-hosts/releases/download/v15/clang-r416183b.tar.xz;tar xJf clang-r416183b.tar.xz -C /home/runner/work/kernel_build_action/kernel_build_action/clang/;touch /home/runner/work/kernel_build_action/kernel_build_action/clang/not-linux-tool; rm clang-r416183b.tar.xz
      - name: Get gcc
        run: mkdir /home/runner/work/kernel_build_action/kernel_build_action/gcc-4.9;wget -q https://github.com/tomxi1997/Toolchain-for-aarch64-hosts/releases/download/v6/google_gcc-4.9-main-20240120.tar.xz;tar xJf google_gcc-4.9-main-20240120.tar.xz -C /home/runner/work/kernel_build_action/kernel_build_action/gcc-4.9/;rm google_gcc-4.9-main-20240120.tar.xz
      - name: Build Kernel
        id: gmake_build
        uses: cora4/kernel_build_action@main
        with:
          kernel-url: https://github.com/cora4/kernel_red
          kernel-dir: msm-5.4
          kernel-branch: 11
          config: gki_defconfig
          arch: arm64
          aosp-gcc: false
          aosp-clang: false
          other-clang-url: ./clang/
          other-gcc64-url: ./gcc-4.9/
          anykernel3: true
          android-version: 12
          aosp-clang-version: r416183b1
          ccache: true
          disable-lto: false
          extra-make-args: '[
            "LLVM=1",
            "LLVM_IAS=1"
           ]'
      - name: Upload Build Artifact
        if: ${{ always() && steps.gmake_build.outcome == 'success' }}
        uses: actions/upload-artifact@v6
        with:
          name: gki-kernel
          path: kernel/msm-5.4/out/arch/arm64/boot
