# A simple action usage
name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-22.04-arm
    permissions:
      contents: read
    steps:
      - name: Install libc6-dev-i386 lib32gcc-11-dev
        run: sudo apt install libc6-dev-i386 lib32gcc-11-dev
      - name: Build Kernel
        id: gmake_build
        uses: cora4/kernel_build_action@main
        with:
          kernel-url: https://github.com/cora4/kernel_red
          kernel-dir: msm-5.4
          kernel-branch: 11
          config: gki_defconfig
          arch: arm64
          aosp-gcc: false
          aosp-clang: false
          other-clang-url: https://github.com/cora4/kernel_red/releases/download/clang/clang-r416183b1.tar.gz
          anykernel3: true
          android-version: 12
          aosp-clang-version: r416183b1
          ccache: true
          disable-lto: false
          extra-make-args: '[
            "LLVM=1",
            "LLVM_IAS=1"
           ]'
      - name: Upload Build Artifact
        if: ${{ always() && steps.gmake_build.outcome == 'success' }}
        uses: actions/upload-artifact@v6
        with:
          name: gki-kernel
          path: kernel/msm-5.4/out/arch/arm64/boot
