name: Build and Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build artifact
        run: |
          mkdir -p dist
          wget https://huggingface.co/prism-ml/Ternary-Bonsai-4B-gguf/resolve/main/Ternary-Bonsai-4B-Q2_0.gguf?download=true
          mv Ternary-Bonsai-4B-Q2_0.gguf?download=true qwen3-4B-Q2_0.gguf

      - name: Create Release
        run: |
          TAG=main-${{ github.run_number }}-$RANDOM
          git tag $TAG
          git push origin $TAG
          gh release create $TAG qwen3-4B-Q2_0.gguf \
            --title "Release $TAG"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
